# Independent settings for the local costmap
local_costmap:
  map_type: costmap

  global_frame    : odom
  robot_base_frame: base_footprint

  update_frequency : 5.0
  publish_frequency: 1.0

  static_map    : false
  rolling_window: true
  width         : 4.0
  height        : 4.0
  resolution    : 0.025

  robot_radius: 0.275

  #plugins are loaded on a separate file

  obstacle_laser_layer:
    enabled: true
    observation_sources: base_scan rgbd_to_laser
    combination_method: 0 # can erase static layer

    base_scan:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: scan
      expected_update_rate: 0.3
      observation_persistence: 0.0
      inf_is_valid: true
      marking: true
      clearing: False
      raytrace_range: 4.0
      obstacle_range: 3.0

    rgbd_to_laser:
      sensor_frame: rgbd_laser_link
      data_type: LaserScan
      topic: rgbd_scan
      expected_update_rate: 0.3
      observation_persistence: 0.0
      inf_is_valid: true
      marking: true
      clearing: False
      raytrace_range: 4.0
      obstacle_range: 3.0

  obstacle_sonar_layer:
    enabled: false
    ns: ""
    topics: ["/sonar_base"]
    no_readings_timeout: 0.0
    clear_threshold: 0.20
    mark_threshold: 0.80
    clear_on_max_reading: true


    
      
  voxel_layer:
    # plugin: "nav2_costmap_2d::VoxelLayer"
    # map_type: voxel

    enabled: false
    footprint_clearing_enabled: true
    max_obstacle_height: 2.0
    # publish_voxel_map: True
    origin_z: 0.0
    z_resolution: 0.05
    z_voxels: 15
    max_obstacle_height: 2.0
    unknown_threshold: 5
    mark_threshold: 5
    observation_sources: point_cloud
    combination_method: 0

    point_cloud:  # no frame set, uses frame from message
      sensor_frame: xtion_rgb_optical_frame
      topic: /filtered_pcl_4voxel
      max_obstacle_height: 1.5
      min_obstacle_height: 0.0
      obstacle_max_range: 2.5
      obstacle_min_range: 0.0
      clearing: True
      marking: True
      data_type: "PointCloud2"

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.2
    cost_scaling_factor: 5.0
