voxel_layer:
    # plugin: "nav2_costmap_2d::VoxelLayer"
    # map_type: voxel

    enabled: True
    footprint_clearing_enabled: true
    max_obstacle_height: 2.0
    # publish_voxel_map: True
    origin_z: 0.0
    z_resolution: 0.1
    z_voxels: 15
    max_obstacle_height: 2.0
    unknown_threshold: 5
    mark_threshold: 5
    observation_sources: point_cloud
    combination_method: 0

    point_cloud:  # no frame set, uses frame from message
      sensor_frame: xtion_rgb_optical_frame
      topic: /filtered_pcl_4voxel
      max_obstacle_height: 1.5
      min_obstacle_height: 0.0
      obstacle_max_range: 2.5
      obstacle_min_range: 0.0
      clearing: True
      marking: True
      data_type: "PointCloud2"

 
 
